Week categories
913-RichardOrr/caliber-mobile pull request #19
Opened 2021-02-17 16:41 UTC by kwood98

Tests written for weekCategory.component, weekCategoreList, and weekCategoryService

2021-02-17 16:45 UTC, RevatureGentry approved these changes

2021-02-19 17:58 UTC, rlayneorr commented
Please resolve the "bug" that SonarCloud is indicating.

2021-02-22 17:02 UTC, RevatureGentry commented on store/WeekCategoryReducer.ts
> +        case Actions.WeekCategoryActions.GetWeekCategories:
This action type has a misleading name - the name implies a read, and it shares the same functionality as `Actions.WeekCategoryActions.ChangeWeekCategories`, but it overwrites the existing `weekCategories` in state with the action's payload. Is this intentional?

2021-02-22 17:09 UTC, RevatureGentry commented on weekCategories/WeekCategoryComponent.tsx
> +    <Text style={styles.myFontColor}>{categoryContext+"  "}
Do we have the two whitespaces here to horizontally align the `categoryContext` with the `x` button?

2021-02-22 17:19 UTC, RevatureGentry requested changes
Consider changing the current action type of `Actions.WeekCategoryActions.GetWeekCategories` into a more appropriate name for the operation.

2021-02-24 22:39 UTC, RevatureGentry approved these changes

2021-03-02 15:54 UTC, RevatureGentry approved these changes

2021-03-02 20:55 UTC, merged